
version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - blog-network
    environment:
      MYSQL_ROOT_PASSWORD: thisrootisawesome
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=MYSQL]
      placement:
        constraints:
        - node.role == manager

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    networks:
      - blog-network
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=WORDPRESS]

networks:
  blog-network:
volumes:
  db_data: {}
  wp_data: {}